### ISSUE TITLE
Templating leader name does not work

### ISSUE THREAD

**Issue by ghost** [dkantereivin/pnw-pyrecruiter#2]
Here's a screenshot to try and show what I'm experiencing! 
<img width="642" alt="Screen Shot 2020-10-21 at 10 40 46 PM" src="https://user-images.githubusercontent.com/66393553/96821970-994c7100-13ee-11eb-99bf-5bb6a086d202.png">
<img width="826" alt="Screen Shot 2020-10-21 at 10 44 59 PM" src="https://user-images.githubusercontent.com/66393553/96822171-0eb84180-13ef-11eb-8b47-f7664d4c7db3.png">

**Comment by dkantereivin** [comment]
Will investigate. This is odd, not heard of anyone else experiencing this. It's also not officially supported according the docs, and it should be, so I might need to update this.

As a todo, it might be worth implementing arithmetic logic using `exec` at the same time, although this would be a seperate PR.
