### ISSUE TITLE
Restriction on messaging new nations

### ISSUE THREAD

**Issue by yoda8** [dkantereivin/pnw-pyrecruiter#6]
Some nations cannot be messaged as they were too new (less than 3 minutes old). The bot said that the messages were sent, but they were not actually sent.

![restriction](https://user-images.githubusercontent.com/80381604/110588235-b7551b00-81af-11eb-8417-a3addd324c81.png)

**Comment by dkantereivin** [comment]
I don't think this is a substantial issue, since it will still send them the message once the 3 minutes pass.
